<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipioSeeder extends Seeder
{
    public function run(): void
    {
        $municipios = [
            ['id_municipio' =>   1, 'municipio' => 'AHUACHAPÁN', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 1],
            ['id_municipio' =>   2, 'municipio' => 'APANECA', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 1],
            ['id_municipio' =>   3, 'municipio' => 'ATIQUIZAYA', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 1],
            ['id_municipio' =>   4, 'municipio' => 'CONCEPCIÓN DE ATACO', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 1],
            ['id_municipio' =>   5, 'municipio' => 'EL REFUGIO', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 1],
            ['id_municipio' =>   6, 'municipio' => 'GUAYMANGO', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 1],
            ['id_municipio' =>   7, 'municipio' => 'JUJUTLA', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 1],
            ['id_municipio' =>   8, 'municipio' => 'SAN FRANCISCO MENÉNDEZ', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 1],
            ['id_municipio' =>   9, 'municipio' => 'SAN LORENZO', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 1],
            ['id_municipio' =>  10, 'municipio' => 'SAN PEDRO PUXTLA', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 1],
            ['id_municipio' =>  11, 'municipio' => 'TACUBA', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 1],
            ['id_municipio' =>  12, 'municipio' => 'TURÍN', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 1],
            ['id_municipio' =>  13, 'municipio' => 'CANDELARIA DE LA FRONTERA', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  14, 'municipio' => 'COATEPEQUE', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  15, 'municipio' => 'CHALCHUAPA', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  16, 'municipio' => 'EL CONGO', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  17, 'municipio' => 'EL PORVENIR', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  18, 'municipio' => 'MASAHUAT', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  19, 'municipio' => 'METAPÁN', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  20, 'municipio' => 'SAN ANTONIO PAJONAL', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  21, 'municipio' => 'SAN SEBASTIÁN SALITRILLO', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  22, 'municipio' => 'SANTA ANA', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  23, 'municipio' => 'STA ROSA GUACHI', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  24, 'municipio' => 'STGO D LA FRONT', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  25, 'municipio' => 'TEXISTEPEQUE', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 2],
            ['id_municipio' =>  26, 'municipio' => 'ACAJUTLA', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  27, 'municipio' => 'ARMENIA', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  28, 'municipio' => 'CALUCO', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  29, 'municipio' => 'CUISNAHUAT', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  30, 'municipio' => 'STA I ISHUATAN', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  31, 'municipio' => 'IZALCO', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  32, 'municipio' => 'JUAYÚA', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  33, 'municipio' => 'NAHUIZALCO', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  34, 'municipio' => 'NAHULINGO', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  35, 'municipio' => 'SALCOATITÁN', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  36, 'municipio' => 'SAN ANTONIO DEL MONTE', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  37, 'municipio' => 'SAN JULIÁN', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  38, 'municipio' => 'STA C MASAHUAT', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  39, 'municipio' => 'SANTO DOMINGO GUZMÁN', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  40, 'municipio' => 'SONSONATE', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  41, 'municipio' => 'SONZACATE', 'cod_mh_municipio' => '16', 'cod_mh_departamento' => 3],
            ['id_municipio' =>  42, 'municipio' => 'AGUA CALIENTE', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  43, 'municipio' => 'ARCATAO', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  44, 'municipio' => 'AZACUALPA', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  45, 'municipio' => 'CITALÁ', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  46, 'municipio' => 'COMALAPA', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  47, 'municipio' => 'CONCEPCIÓN QUEZALTEPEQUE', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  48, 'municipio' => 'CHALATENANGO', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  49, 'municipio' => 'DULCE NOM MARÍA', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  50, 'municipio' => 'EL CARRIZAL', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  51, 'municipio' => 'EL PARAÍSO', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  52, 'municipio' => 'LA LAGUNA', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  53, 'municipio' => 'LA PALMA', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  54, 'municipio' => 'LA REINA', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  55, 'municipio' => 'LAS VUELTAS', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  56, 'municipio' => 'NOMBRE DE JESUS', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  57, 'municipio' => 'NVA CONCEPCIÓN', 'cod_mh_municipio' => '16', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  58, 'municipio' => 'NUEVA TRINIDAD', 'cod_mh_municipio' => '17', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  59, 'municipio' => 'OJOS DE AGUA', 'cod_mh_municipio' => '18', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  60, 'municipio' => 'POTONICO', 'cod_mh_municipio' => '19', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  61, 'municipio' => 'SAN ANT LA CRUZ', 'cod_mh_municipio' => '20', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  62, 'municipio' => 'SAN ANT RANCHOS', 'cod_mh_municipio' => '21', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  63, 'municipio' => 'SAN FERNANDO', 'cod_mh_municipio' => '22', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  64, 'municipio' => 'SAN FRANCISCO LEMPA', 'cod_mh_municipio' => '23', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  65, 'municipio' => 'SAN FRANCISCO MORAZÁN', 'cod_mh_municipio' => '24', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  66, 'municipio' => 'SAN IGNACIO', 'cod_mh_municipio' => '25', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  67, 'municipio' => 'SAN I LABRADOR', 'cod_mh_municipio' => '26', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  68, 'municipio' => 'SAN J CANCASQUE', 'cod_mh_municipio' => '27', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  69, 'municipio' => 'SAN JOSE FLORES', 'cod_mh_municipio' => '28', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  70, 'municipio' => 'SAN LUIS CARMEN', 'cod_mh_municipio' => '29', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  71, 'municipio' => 'SN MIG MERCEDES', 'cod_mh_municipio' => '30', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  72, 'municipio' => 'SAN RAFAEL', 'cod_mh_municipio' => '31', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  73, 'municipio' => 'SANTA RITA', 'cod_mh_municipio' => '32', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  74, 'municipio' => 'TEJUTLA', 'cod_mh_municipio' => '33', 'cod_mh_departamento' => 4],
            ['id_municipio' =>  75, 'municipio' => 'ANTGO CUSCATLÁN', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  76, 'municipio' => 'CIUDAD ARCE', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  77, 'municipio' => 'COLON', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  78, 'municipio' => 'COMASAGUA', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  79, 'municipio' => 'CHILTIUPAN', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  80, 'municipio' => 'HUIZÚCAR', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  81, 'municipio' => 'JAYAQUE', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  82, 'municipio' => 'JICALAPA', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  83, 'municipio' => 'LA LIBERTAD', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  84, 'municipio' => 'NUEVO CUSCATLÁN', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  85, 'municipio' => 'SANTA TECLA', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  86, 'municipio' => 'QUEZALTEPEQUE', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  87, 'municipio' => 'SACACOYO', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  88, 'municipio' => 'SN J VILLANUEVA', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  89, 'municipio' => 'SAN JUAN OPICO', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  90, 'municipio' => 'SAN MATÍAS', 'cod_mh_municipio' => '16', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  91, 'municipio' => 'SAN P TACACHICO', 'cod_mh_municipio' => '17', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  92, 'municipio' => 'TAMANIQUE', 'cod_mh_municipio' => '18', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  93, 'municipio' => 'TALNIQUE', 'cod_mh_municipio' => '19', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  94, 'municipio' => 'TEOTEPEQUE', 'cod_mh_municipio' => '20', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  95, 'municipio' => 'TEPECOYO', 'cod_mh_municipio' => '21', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  96, 'municipio' => 'ZARAGOZA', 'cod_mh_municipio' => '22', 'cod_mh_departamento' => 5],
            ['id_municipio' =>  97, 'municipio' => 'AGUILARES', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 6],
            ['id_municipio' =>  98, 'municipio' => 'APOPA', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 6],
            ['id_municipio' =>  99, 'municipio' => 'AYUTUXTEPEQUE', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 6],
            ['id_municipio' => 100, 'municipio' => 'CUSCATANCINGO', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 6],
            ['id_municipio' => 101, 'municipio' => 'EL PAISNAL', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 6],
            ['id_municipio' => 102, 'municipio' => 'GUAZAPA', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 6],
            ['id_municipio' => 103, 'municipio' => 'ILOPANGO', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 6],
            ['id_municipio' => 104, 'municipio' => 'MEJICANOS', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 6],
            ['id_municipio' => 105, 'municipio' => 'NEJAPA', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 6],
            ['id_municipio' => 106, 'municipio' => 'PANCHIMALCO', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 6],
            ['id_municipio' => 107, 'municipio' => 'ROSARIO DE MORA', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 6],
            ['id_municipio' => 108, 'municipio' => 'SAN MARCOS', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 6],
            ['id_municipio' => 109, 'municipio' => 'SAN MARTIN', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 6],
            ['id_municipio' => 110, 'municipio' => 'SAN SALVADOR', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 6],
            ['id_municipio' => 111, 'municipio' => 'STG TEXACUANGOS', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 6],
            ['id_municipio' => 112, 'municipio' => 'SANTO TOMAS', 'cod_mh_municipio' => '16', 'cod_mh_departamento' => 6],
            ['id_municipio' => 113, 'municipio' => 'SOYAPANGO', 'cod_mh_municipio' => '17', 'cod_mh_departamento' => 6],
            ['id_municipio' => 114, 'municipio' => 'TONACATEPEQUE', 'cod_mh_municipio' => '18', 'cod_mh_departamento' => 6],
            ['id_municipio' => 115, 'municipio' => 'CIUDAD DELGADO', 'cod_mh_municipio' => '19', 'cod_mh_departamento' => 6],
            ['id_municipio' => 116, 'municipio' => 'CANDELARIA', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 7],
            ['id_municipio' => 117, 'municipio' => 'COJUTEPEQUE', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 7],
            ['id_municipio' => 118, 'municipio' => 'EL CARMEN', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 7],
            ['id_municipio' => 119, 'municipio' => 'EL ROSARIO', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 7],
            ['id_municipio' => 120, 'municipio' => 'MONTE SAN JUAN', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 7],
            ['id_municipio' => 121, 'municipio' => 'ORAT CONCEPCIÓN', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 7],
            ['id_municipio' => 122, 'municipio' => 'SAN B PERULAPIA', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 7],
            ['id_municipio' => 123, 'municipio' => 'SAN CRISTÓBAL', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 7],
            ['id_municipio' => 124, 'municipio' => 'SAN J GUAYABAL', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 7],
            ['id_municipio' => 125, 'municipio' => 'SAN P PERULAPÁN', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 7],
            ['id_municipio' => 126, 'municipio' => 'SAN RAF CEDROS', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 7],
            ['id_municipio' => 127, 'municipio' => 'SAN RAMON', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 7],
            ['id_municipio' => 128, 'municipio' => 'STA C ANALQUITO', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 7],
            ['id_municipio' => 129, 'municipio' => 'STA C MICHAPA', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 7],
            ['id_municipio' => 130, 'municipio' => 'SUCHITOTO', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 7],
            ['id_municipio' => 131, 'municipio' => 'TENANCINGO', 'cod_mh_municipio' => '16', 'cod_mh_departamento' => 7],
            ['id_municipio' => 132, 'municipio' => 'CUYULTITÁN', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 8],
            ['id_municipio' => 133, 'municipio' => 'EL ROSARIO', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 8],
            ['id_municipio' => 134, 'municipio' => 'JERUSALÉN', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 8],
            ['id_municipio' => 135, 'municipio' => 'MERCED LA CEIBA', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 8],
            ['id_municipio' => 136, 'municipio' => 'OLOCUILTA', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 8],
            ['id_municipio' => 137, 'municipio' => 'PARAÍSO OSORIO', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 8],
            ['id_municipio' => 138, 'municipio' => 'SN ANT MASAHUAT', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 8],
            ['id_municipio' => 139, 'municipio' => 'SAN EMIGDIO', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 8],
            ['id_municipio' => 140, 'municipio' => 'SN FCO CHINAMEC', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 8],
            ['id_municipio' => 141, 'municipio' => 'SAN J NONUALCO', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 8],
            ['id_municipio' => 142, 'municipio' => 'SAN JUAN TALPA', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 8],
            ['id_municipio' => 143, 'municipio' => 'SAN JUAN TEPEZONTES', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 8],
            ['id_municipio' => 144, 'municipio' => 'SAN LUIS TALPA', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 8],
            ['id_municipio' => 145, 'municipio' => 'SAN MIGUEL TEPEZONTES', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 8],
            ['id_municipio' => 146, 'municipio' => 'SAN PEDRO MASAHUAT', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 8],
            ['id_municipio' => 147, 'municipio' => 'SAN PEDRO NONUALCO', 'cod_mh_municipio' => '16', 'cod_mh_departamento' => 8],
            ['id_municipio' => 148, 'municipio' => 'SAN R OBRAJUELO', 'cod_mh_municipio' => '17', 'cod_mh_departamento' => 8],
            ['id_municipio' => 149, 'municipio' => 'STA MA OSTUMA', 'cod_mh_municipio' => '18', 'cod_mh_departamento' => 8],
            ['id_municipio' => 150, 'municipio' => 'STGO NONUALCO', 'cod_mh_municipio' => '19', 'cod_mh_departamento' => 8],
            ['id_municipio' => 151, 'municipio' => 'TAPALHUACA', 'cod_mh_municipio' => '20', 'cod_mh_departamento' => 8],
            ['id_municipio' => 152, 'municipio' => 'ZACATECOLUCA', 'cod_mh_municipio' => '21', 'cod_mh_departamento' => 8],
            ['id_municipio' => 153, 'municipio' => 'SN LUIS LA HERR', 'cod_mh_municipio' => '22', 'cod_mh_departamento' => 8],
            ['id_municipio' => 154, 'municipio' => 'CINQUERA', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 9],
            ['id_municipio' => 155, 'municipio' => 'GUACOTECTI', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 9],
            ['id_municipio' => 156, 'municipio' => 'ILOBASCO', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 9],
            ['id_municipio' => 157, 'municipio' => 'JUTIAPA', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 9],
            ['id_municipio' => 158, 'municipio' => 'SAN ISIDRO', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 9],
            ['id_municipio' => 159, 'municipio' => 'SENSUNTEPEQUE', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 9],
            ['id_municipio' => 160, 'municipio' => 'TEJUTEPEQUE', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 9],
            ['id_municipio' => 161, 'municipio' => 'VICTORIA', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 9],
            ['id_municipio' => 162, 'municipio' => 'DOLORES', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 9],
            ['id_municipio' => 163, 'municipio' => 'APASTEPEQUE', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 10],
            ['id_municipio' => 164, 'municipio' => 'GUADALUPE', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 10],
            ['id_municipio' => 165, 'municipio' => 'SAN CAY ISTEPEQ', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 10],
            ['id_municipio' => 166, 'municipio' => 'SANTA CLARA', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 10],
            ['id_municipio' => 167, 'municipio' => 'SANTO DOMINGO', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 10],
            ['id_municipio' => 168, 'municipio' => 'SN EST CATARINA', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 10],
            ['id_municipio' => 169, 'municipio' => 'SAN ILDEFONSO', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 10],
            ['id_municipio' => 170, 'municipio' => 'SAN LORENZO', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 10],
            ['id_municipio' => 171, 'municipio' => 'SAN SEBASTIÁN', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 10],
            ['id_municipio' => 172, 'municipio' => 'SAN VICENTE', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 10],
            ['id_municipio' => 173, 'municipio' => 'TECOLUCA', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 10],
            ['id_municipio' => 174, 'municipio' => 'TEPETITÁN', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 10],
            ['id_municipio' => 175, 'municipio' => 'VERAPAZ', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 10],
            ['id_municipio' => 176, 'municipio' => 'ALEGRÍA', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 11],
            ['id_municipio' => 177, 'municipio' => 'BERLÍN', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 11],
            ['id_municipio' => 178, 'municipio' => 'CALIFORNIA', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 11],
            ['id_municipio' => 179, 'municipio' => 'CONCEP BATRES', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 11],
            ['id_municipio' => 180, 'municipio' => 'EL TRIUNFO', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 11],
            ['id_municipio' => 181, 'municipio' => 'EREGUAYQUÍN', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 11],
            ['id_municipio' => 182, 'municipio' => 'ESTANZUELAS', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 11],
            ['id_municipio' => 183, 'municipio' => 'JIQUILISCO', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 11],
            ['id_municipio' => 184, 'municipio' => 'JUCUAPA', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 11],
            ['id_municipio' => 185, 'municipio' => 'JUCUARÁN', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 11],
            ['id_municipio' => 186, 'municipio' => 'MERCEDES UMAÑA', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 11],
            ['id_municipio' => 187, 'municipio' => 'NUEVA GRANADA', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 11],
            ['id_municipio' => 188, 'municipio' => 'OZATLÁN', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 11],
            ['id_municipio' => 189, 'municipio' => 'PTO EL TRIUNFO', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 11],
            ['id_municipio' => 190, 'municipio' => 'SAN AGUSTÍN', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 11],
            ['id_municipio' => 191, 'municipio' => 'SN BUENAVENTURA', 'cod_mh_municipio' => '16', 'cod_mh_departamento' => 11],
            ['id_municipio' => 192, 'municipio' => 'SAN DIONISIO', 'cod_mh_municipio' => '17', 'cod_mh_departamento' => 11],
            ['id_municipio' => 193, 'municipio' => 'SANTA ELENA', 'cod_mh_municipio' => '18', 'cod_mh_departamento' => 11],
            ['id_municipio' => 194, 'municipio' => 'SAN FCO JAVIER', 'cod_mh_municipio' => '19', 'cod_mh_departamento' => 11],
            ['id_municipio' => 195, 'municipio' => 'SANTA MARÍA', 'cod_mh_municipio' => '20', 'cod_mh_departamento' => 11],
            ['id_municipio' => 196, 'municipio' => 'STGO DE MARÍA', 'cod_mh_municipio' => '21', 'cod_mh_departamento' => 11],
            ['id_municipio' => 197, 'municipio' => 'TECAPÁN', 'cod_mh_municipio' => '22', 'cod_mh_departamento' => 11],
            ['id_municipio' => 198, 'municipio' => 'USULUTÁN', 'cod_mh_municipio' => '23', 'cod_mh_departamento' => 11],
            ['id_municipio' => 199, 'municipio' => 'CAROLINA', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 12],
            ['id_municipio' => 200, 'municipio' => 'CIUDAD BARRIOS', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 12],
            ['id_municipio' => 201, 'municipio' => 'COMACARÁN', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 12],
            ['id_municipio' => 202, 'municipio' => 'CHAPELTIQUE', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 12],
            ['id_municipio' => 203, 'municipio' => 'CHINAMECA', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 12],
            ['id_municipio' => 204, 'municipio' => 'CHIRILAGUA', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 12],
            ['id_municipio' => 205, 'municipio' => 'EL TRANSITO', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 12],
            ['id_municipio' => 206, 'municipio' => 'LOLOTIQUE', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 12],
            ['id_municipio' => 207, 'municipio' => 'MONCAGUA', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 12],
            ['id_municipio' => 208, 'municipio' => 'NUEVA GUADALUPE', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 12],
            ['id_municipio' => 209, 'municipio' => 'NVO EDÉN S JUAN', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 12],
            ['id_municipio' => 210, 'municipio' => 'QUELEPA', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 12],
            ['id_municipio' => 211, 'municipio' => 'SAN ANT D MOSCO', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 12],
            ['id_municipio' => 212, 'municipio' => 'SAN GERARDO', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 12],
            ['id_municipio' => 213, 'municipio' => 'SAN JORGE', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 12],
            ['id_municipio' => 214, 'municipio' => 'SAN LUIS REINA', 'cod_mh_municipio' => '16', 'cod_mh_departamento' => 12],
            ['id_municipio' => 215, 'municipio' => 'SAN MIGUEL', 'cod_mh_municipio' => '17', 'cod_mh_departamento' => 12],
            ['id_municipio' => 216, 'municipio' => 'SAN RAF ORIENTE', 'cod_mh_municipio' => '18', 'cod_mh_departamento' => 12],
            ['id_municipio' => 217, 'municipio' => 'SESORI', 'cod_mh_municipio' => '19', 'cod_mh_departamento' => 12],
            ['id_municipio' => 218, 'municipio' => 'ULUAZAPA', 'cod_mh_municipio' => '20', 'cod_mh_departamento' => 12],
            ['id_municipio' => 219, 'municipio' => 'ARAMBALA', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 13],
            ['id_municipio' => 220, 'municipio' => 'CACAOPERA', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 13],
            ['id_municipio' => 221, 'municipio' => 'CORINTO', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 13],
            ['id_municipio' => 222, 'municipio' => 'CHILANGA', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 13],
            ['id_municipio' => 223, 'municipio' => 'DELIC DE CONCEP', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 13],
            ['id_municipio' => 224, 'municipio' => 'EL DIVISADERO', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 13],
            ['id_municipio' => 225, 'municipio' => 'EL ROSARIO', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 13],
            ['id_municipio' => 226, 'municipio' => 'GUALOCOCTI', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 13],
            ['id_municipio' => 227, 'municipio' => 'GUATAJIAGUA', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 13],
            ['id_municipio' => 228, 'municipio' => 'JOATECA', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 13],
            ['id_municipio' => 229, 'municipio' => 'JOCOAITIQUE', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 13],
            ['id_municipio' => 230, 'municipio' => 'JOCORO', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 13],
            ['id_municipio' => 231, 'municipio' => 'LOLOTIQUILLO', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 13],
            ['id_municipio' => 232, 'municipio' => 'MEANGUERA', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 13],
            ['id_municipio' => 233, 'municipio' => 'OSICALA', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 13],
            ['id_municipio' => 234, 'municipio' => 'PERQUÍN', 'cod_mh_municipio' => '16', 'cod_mh_departamento' => 13],
            ['id_municipio' => 235, 'municipio' => 'SAN CARLOS', 'cod_mh_municipio' => '17', 'cod_mh_departamento' => 13],
            ['id_municipio' => 236, 'municipio' => 'SAN FERNANDO', 'cod_mh_municipio' => '18', 'cod_mh_departamento' => 13],
            ['id_municipio' => 237, 'municipio' => 'SAN FCO GOTERA', 'cod_mh_municipio' => '19', 'cod_mh_departamento' => 13],
            ['id_municipio' => 238, 'municipio' => 'SAN ISIDRO', 'cod_mh_municipio' => '20', 'cod_mh_departamento' => 13],
            ['id_municipio' => 239, 'municipio' => 'SAN SIMÓN', 'cod_mh_municipio' => '21', 'cod_mh_departamento' => 13],
            ['id_municipio' => 240, 'municipio' => 'SENSEMBRA', 'cod_mh_municipio' => '22', 'cod_mh_departamento' => 13],
            ['id_municipio' => 241, 'municipio' => 'SOCIEDAD', 'cod_mh_municipio' => '23', 'cod_mh_departamento' => 13],
            ['id_municipio' => 242, 'municipio' => 'TOROLA', 'cod_mh_municipio' => '24', 'cod_mh_departamento' => 13],
            ['id_municipio' => 243, 'municipio' => 'YAMABAL', 'cod_mh_municipio' => '25', 'cod_mh_departamento' => 13],
            ['id_municipio' => 244, 'municipio' => 'YOLOAIQUÍN', 'cod_mh_municipio' => '26', 'cod_mh_departamento' => 13],
            ['id_municipio' => 245, 'municipio' => 'ANAMOROS', 'cod_mh_municipio' => '01', 'cod_mh_departamento' => 14],
            ['id_municipio' => 246, 'municipio' => 'BOLÍVAR', 'cod_mh_municipio' => '02', 'cod_mh_departamento' => 14],
            ['id_municipio' => 247, 'municipio' => 'CONCEP DE OTE', 'cod_mh_municipio' => '03', 'cod_mh_departamento' => 14],
            ['id_municipio' => 248, 'municipio' => 'CONCHAGUA', 'cod_mh_municipio' => '04', 'cod_mh_departamento' => 14],
            ['id_municipio' => 249, 'municipio' => 'EL CARMEN', 'cod_mh_municipio' => '05', 'cod_mh_departamento' => 14],
            ['id_municipio' => 250, 'municipio' => 'EL SAUCE', 'cod_mh_municipio' => '06', 'cod_mh_departamento' => 14],
            ['id_municipio' => 251, 'municipio' => 'INTIPUCÁ', 'cod_mh_municipio' => '07', 'cod_mh_departamento' => 14],
            ['id_municipio' => 252, 'municipio' => 'LA UNIÓN', 'cod_mh_municipio' => '08', 'cod_mh_departamento' => 14],
            ['id_municipio' => 253, 'municipio' => 'LISLIQUE', 'cod_mh_municipio' => '09', 'cod_mh_departamento' => 14],
            ['id_municipio' => 254, 'municipio' => 'MEANG DEL GOLFO', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 14],
            ['id_municipio' => 255, 'municipio' => 'NUEVA ESPARTA', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 14],
            ['id_municipio' => 256, 'municipio' => 'PASAQUINA', 'cod_mh_municipio' => '12', 'cod_mh_departamento' => 14],
            ['id_municipio' => 257, 'municipio' => 'POLORÓS', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 14],
            ['id_municipio' => 258, 'municipio' => 'SAN ALEJO', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 14],
            ['id_municipio' => 259, 'municipio' => 'SAN JOSE', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 14],
            ['id_municipio' => 260, 'municipio' => 'SANTA ROSA LIMA', 'cod_mh_municipio' => '16', 'cod_mh_departamento' => 14],
            ['id_municipio' => 261, 'municipio' => 'YAYANTIQUE', 'cod_mh_municipio' => '17', 'cod_mh_departamento' => 14],
            ['id_municipio' => 262, 'municipio' => 'YUCUAIQUÍN', 'cod_mh_municipio' => '18', 'cod_mh_departamento' => 14],
            ['id_municipio' => 263, 'municipio' => 'Ahuachapan Norte', 'cod_mh_municipio' => '13', 'cod_mh_departamento' => 15],
            ['id_municipio' => 264, 'municipio' => 'Ahuachapan Centro', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 15],
            ['id_municipio' => 265, 'municipio' => 'Ahuachapan Este', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 15],
            ['id_municipio' => 266, 'municipio' => 'Santa Ana Norte', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 16],
            ['id_municipio' => 267, 'municipio' => 'Santa Ana Centro', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 16],
            ['id_municipio' => 268, 'municipio' => 'Santa Ana Este', 'cod_mh_municipio' => '16', 'cod_mh_departamento' => 16],
            ['id_municipio' => 269, 'municipio' => 'Santa Ana Oeste', 'cod_mh_municipio' => '17', 'cod_mh_departamento' => 16],
            ['id_municipio' => 270, 'municipio' => 'Sonsonate Norte', 'cod_mh_municipio' => '17', 'cod_mh_departamento' => 17],
            ['id_municipio' => 271, 'municipio' => 'Sonsonate Centro', 'cod_mh_municipio' => '18', 'cod_mh_departamento' => 17],
            ['id_municipio' => 272, 'municipio' => 'Sonsonate Este', 'cod_mh_municipio' => '19', 'cod_mh_departamento' => 17],
            ['id_municipio' => 273, 'municipio' => 'Sonsonate Oeste', 'cod_mh_municipio' => '20', 'cod_mh_departamento' => 17],
            ['id_municipio' => 274, 'municipio' => 'Chalatenango Norte', 'cod_mh_municipio' => '34', 'cod_mh_departamento' => 18],
            ['id_municipio' => 275, 'municipio' => 'Chalatenango Centro', 'cod_mh_municipio' => '35', 'cod_mh_departamento' => 18],
            ['id_municipio' => 276, 'municipio' => 'Chalatenango Sur', 'cod_mh_municipio' => '36', 'cod_mh_departamento' => 18],
            ['id_municipio' => 277, 'municipio' => 'La Libertad Norte', 'cod_mh_municipio' => '23', 'cod_mh_departamento' => 19],
            ['id_municipio' => 278, 'municipio' => 'La Libertad Centro', 'cod_mh_municipio' => '24', 'cod_mh_departamento' => 19],
            ['id_municipio' => 279, 'municipio' => 'La Libertad Oeste', 'cod_mh_municipio' => '25', 'cod_mh_departamento' => 19],
            ['id_municipio' => 280, 'municipio' => 'La Libertad Este', 'cod_mh_municipio' => '26', 'cod_mh_departamento' => 19],
            ['id_municipio' => 281, 'municipio' => 'La Libertad Costa', 'cod_mh_municipio' => '27', 'cod_mh_departamento' => 19],
            ['id_municipio' => 282, 'municipio' => 'La Libertad Sur', 'cod_mh_municipio' => '28', 'cod_mh_departamento' => 19],
            ['id_municipio' => 283, 'municipio' => 'San Salvador Norte', 'cod_mh_municipio' => '20', 'cod_mh_departamento' => 20],
            ['id_municipio' => 284, 'municipio' => 'San Salvador Oeste', 'cod_mh_municipio' => '21', 'cod_mh_departamento' => 20],
            ['id_municipio' => 285, 'municipio' => 'San Salvador Este', 'cod_mh_municipio' => '22', 'cod_mh_departamento' => 20],
            ['id_municipio' => 286, 'municipio' => 'San Salvador Centro', 'cod_mh_municipio' => '23', 'cod_mh_departamento' => 20],
            ['id_municipio' => 287, 'municipio' => 'San Salvador Sur', 'cod_mh_municipio' => '24', 'cod_mh_departamento' => 20],
            ['id_municipio' => 288, 'municipio' => 'Cuscatlan Norte', 'cod_mh_municipio' => '17', 'cod_mh_departamento' => 21],
            ['id_municipio' => 289, 'municipio' => 'Cuscatlan Sur', 'cod_mh_municipio' => '18', 'cod_mh_departamento' => 21],
            ['id_municipio' => 290, 'municipio' => 'La Paz Oeste', 'cod_mh_municipio' => '23', 'cod_mh_departamento' => 22],
            ['id_municipio' => 291, 'municipio' => 'La Paz Centro', 'cod_mh_municipio' => '24', 'cod_mh_departamento' => 22],
            ['id_municipio' => 292, 'municipio' => 'La Paz Este', 'cod_mh_municipio' => '25', 'cod_mh_departamento' => 22],
            ['id_municipio' => 293, 'municipio' => 'Cabañas Oeste', 'cod_mh_municipio' => '10', 'cod_mh_departamento' => 23],
            ['id_municipio' => 294, 'municipio' => 'Cabañas Este', 'cod_mh_municipio' => '11', 'cod_mh_departamento' => 23],
            ['id_municipio' => 295, 'municipio' => 'San Vicente Norte', 'cod_mh_municipio' => '14', 'cod_mh_departamento' => 24],
            ['id_municipio' => 296, 'municipio' => 'San Vicente Sur', 'cod_mh_municipio' => '15', 'cod_mh_departamento' => 24],
            ['id_municipio' => 297, 'municipio' => 'Usulutan Norte', 'cod_mh_municipio' => '24', 'cod_mh_departamento' => 25],
            ['id_municipio' => 298, 'municipio' => 'Usulutan Este', 'cod_mh_municipio' => '25', 'cod_mh_departamento' => 25],
            ['id_municipio' => 299, 'municipio' => 'Usulutan Oeste', 'cod_mh_municipio' => '26', 'cod_mh_departamento' => 25],
            ['id_municipio' => 300, 'municipio' => 'San Miguel Norte', 'cod_mh_municipio' => '21', 'cod_mh_departamento' => 26],
            ['id_municipio' => 301, 'municipio' => 'San Miguel Centro', 'cod_mh_municipio' => '22', 'cod_mh_departamento' => 26],
            ['id_municipio' => 302, 'municipio' => 'San Miguel Oeste', 'cod_mh_municipio' => '23', 'cod_mh_departamento' => 26],
            ['id_municipio' => 303, 'municipio' => 'Morazan Norte', 'cod_mh_municipio' => '27', 'cod_mh_departamento' => 27],
            ['id_municipio' => 304, 'municipio' => 'Morazan Sur', 'cod_mh_municipio' => '28', 'cod_mh_departamento' => 27],
            ['id_municipio' => 305, 'municipio' => 'Union Norte', 'cod_mh_municipio' => '19', 'cod_mh_departamento' => 28],
            ['id_municipio' => 306, 'municipio' => 'Union Sur', 'cod_mh_municipio' => '20', 'cod_mh_departamento' => 28],
            ['id_municipio' => 307, 'municipio' => 'Otro (Para extranjeros)', 'cod_mh_municipio' => '00', 'cod_mh_departamento' => 29],
        ];

        foreach (array_chunk($municipios, 50) as $chunk) {
            DB::table('venta_mh_municipio')->insert($chunk);
        }
    }
}
