<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('venta_mh_pais')->insert([
            ['id_pais' =>   1, 'nombre_pais' => 'AFGANISTÁN',                     'estado' => 1],
            ['id_pais' =>   2, 'nombre_pais' => 'ALBANIA',                         'estado' => 1],
            ['id_pais' =>   3, 'nombre_pais' => 'ALEMANIA',                        'estado' => 1],
            ['id_pais' =>   4, 'nombre_pais' => 'ANDORRA',                         'estado' => 1],
            ['id_pais' =>   5, 'nombre_pais' => 'ANGOLA',                          'estado' => 1],
            ['id_pais' =>   6, 'nombre_pais' => 'ANTIGUA Y BARBUDA',               'estado' => 1],
            ['id_pais' =>   7, 'nombre_pais' => 'ARABIA SAUDITA',                  'estado' => 1],
            ['id_pais' =>   8, 'nombre_pais' => 'ARGELIA',                         'estado' => 1],
            ['id_pais' =>   9, 'nombre_pais' => 'ARGENTINA',                       'estado' => 1],
            ['id_pais' =>  10, 'nombre_pais' => 'ARMENIA',                         'estado' => 1],
            ['id_pais' =>  11, 'nombre_pais' => 'AUSTRALIA',                       'estado' => 1],
            ['id_pais' =>  12, 'nombre_pais' => 'AUSTRIA',                         'estado' => 1],
            ['id_pais' =>  13, 'nombre_pais' => 'AZERBAIYÁN',                      'estado' => 1],
            ['id_pais' =>  14, 'nombre_pais' => 'BAHAMAS',                         'estado' => 1],
            ['id_pais' =>  15, 'nombre_pais' => 'BAHREIN',                         'estado' => 1],
            ['id_pais' =>  16, 'nombre_pais' => 'BANGLADESH',                      'estado' => 1],
            ['id_pais' =>  17, 'nombre_pais' => 'BARBADOS',                        'estado' => 1],
            ['id_pais' =>  18, 'nombre_pais' => 'BELARÚS',                         'estado' => 1],
            ['id_pais' =>  19, 'nombre_pais' => 'BÉLGICA',                         'estado' => 1],
            ['id_pais' =>  20, 'nombre_pais' => 'BELICE',                          'estado' => 1],
            ['id_pais' =>  21, 'nombre_pais' => 'BENÍN',                           'estado' => 1],
            ['id_pais' =>  22, 'nombre_pais' => 'BHUTÁN',                          'estado' => 1],
            ['id_pais' =>  23, 'nombre_pais' => 'BOLIVIA',                         'estado' => 1],
            ['id_pais' =>  24, 'nombre_pais' => 'BOSNIA Y HERZEGOVINA',            'estado' => 1],
            ['id_pais' =>  25, 'nombre_pais' => 'BOTSUANA',                        'estado' => 1],
            ['id_pais' =>  26, 'nombre_pais' => 'BRASIL',                          'estado' => 1],
            ['id_pais' =>  27, 'nombre_pais' => 'BRUNÉI DARUSSALAM',               'estado' => 1],
            ['id_pais' =>  28, 'nombre_pais' => 'BULGARIA',                        'estado' => 1],
            ['id_pais' =>  29, 'nombre_pais' => 'BURKINA FASO',                    'estado' => 1],
            ['id_pais' =>  30, 'nombre_pais' => 'BURUNDI',                         'estado' => 1],
            ['id_pais' =>  31, 'nombre_pais' => 'CABO VERDE',                      'estado' => 1],
            ['id_pais' =>  32, 'nombre_pais' => 'CAMBOYA',                         'estado' => 1],
            ['id_pais' =>  33, 'nombre_pais' => 'CAMERÚN',                         'estado' => 1],
            ['id_pais' =>  34, 'nombre_pais' => 'CANADÁ',                          'estado' => 1],
            ['id_pais' =>  35, 'nombre_pais' => 'CATAR',                           'estado' => 1],
            ['id_pais' =>  36, 'nombre_pais' => 'CHAD',                            'estado' => 1],
            ['id_pais' =>  37, 'nombre_pais' => 'CHILE',                           'estado' => 1],
            ['id_pais' =>  38, 'nombre_pais' => 'CHINA',                           'estado' => 1],
            ['id_pais' =>  39, 'nombre_pais' => 'CHIPRE',                          'estado' => 1],
            ['id_pais' =>  40, 'nombre_pais' => 'COLOMBIA',                        'estado' => 1],
            ['id_pais' =>  41, 'nombre_pais' => 'COMORAS',                         'estado' => 1],
            ['id_pais' =>  42, 'nombre_pais' => 'CONGO',                           'estado' => 1],
            ['id_pais' =>  43, 'nombre_pais' => 'COREA DEL NORTE',                 'estado' => 1],
            ['id_pais' =>  44, 'nombre_pais' => 'COREA DEL SUR',                   'estado' => 1],
            ['id_pais' =>  45, 'nombre_pais' => 'COSTA DE MARFIL',                 'estado' => 1],
            ['id_pais' =>  46, 'nombre_pais' => 'COSTA RICA',                      'estado' => 1],
            ['id_pais' =>  47, 'nombre_pais' => 'CROACIA',                         'estado' => 1],
            ['id_pais' =>  48, 'nombre_pais' => 'CUBA',                            'estado' => 1],
            ['id_pais' =>  49, 'nombre_pais' => 'DINAMARCA',                       'estado' => 1],
            ['id_pais' =>  50, 'nombre_pais' => 'DOMINICA',                        'estado' => 1],
            ['id_pais' =>  51, 'nombre_pais' => 'ECUADOR',                         'estado' => 1],
            ['id_pais' =>  52, 'nombre_pais' => 'EGIPTO',                          'estado' => 1],
            ['id_pais' =>  53, 'nombre_pais' => 'EMIRATOS ÁRABES UNIDOS',          'estado' => 1],
            ['id_pais' =>  54, 'nombre_pais' => 'ERITREA',                         'estado' => 1],
            ['id_pais' =>  55, 'nombre_pais' => 'ESLOVAQUIA',                      'estado' => 1],
            ['id_pais' =>  56, 'nombre_pais' => 'ESLOVENIA',                       'estado' => 1],
            ['id_pais' =>  57, 'nombre_pais' => 'ESPAÑA',                          'estado' => 1],
            ['id_pais' =>  58, 'nombre_pais' => 'ESTADOS UNIDOS DE AMÉRICA',       'estado' => 1],
            ['id_pais' =>  59, 'nombre_pais' => 'ESTONIA',                         'estado' => 1],
            ['id_pais' =>  60, 'nombre_pais' => 'ETIOPÍA',                         'estado' => 1],
            ['id_pais' =>  61, 'nombre_pais' => 'FILIPINAS',                       'estado' => 1],
            ['id_pais' =>  62, 'nombre_pais' => 'FINLANDIA',                       'estado' => 1],
            ['id_pais' =>  63, 'nombre_pais' => 'FIYI',                            'estado' => 1],
            ['id_pais' =>  64, 'nombre_pais' => 'FRANCIA',                         'estado' => 1],
            ['id_pais' =>  65, 'nombre_pais' => 'GABÓN',                           'estado' => 1],
            ['id_pais' =>  66, 'nombre_pais' => 'GAMBIA',                          'estado' => 1],
            ['id_pais' =>  67, 'nombre_pais' => 'GEORGIA',                         'estado' => 1],
            ['id_pais' =>  68, 'nombre_pais' => 'GHANA',                           'estado' => 1],
            ['id_pais' =>  69, 'nombre_pais' => 'GRANADA',                         'estado' => 1],
            ['id_pais' =>  70, 'nombre_pais' => 'GRECIA',                          'estado' => 1],
            ['id_pais' =>  71, 'nombre_pais' => 'GUATEMALA',                       'estado' => 1],
            ['id_pais' =>  72, 'nombre_pais' => 'GUINEA',                          'estado' => 1],
            ['id_pais' =>  73, 'nombre_pais' => 'GUINEA ECUATORIAL',               'estado' => 1],
            ['id_pais' =>  74, 'nombre_pais' => 'GUINEA-BISÁU',                    'estado' => 1],
            ['id_pais' =>  75, 'nombre_pais' => 'GUYANA',                          'estado' => 1],
            ['id_pais' =>  76, 'nombre_pais' => 'HAITÍ',                           'estado' => 1],
            ['id_pais' =>  77, 'nombre_pais' => 'HONDURAS',                        'estado' => 1],
            ['id_pais' =>  78, 'nombre_pais' => 'HUNGRÍA',                         'estado' => 1],
            ['id_pais' =>  79, 'nombre_pais' => 'INDIA',                           'estado' => 1],
            ['id_pais' =>  80, 'nombre_pais' => 'INDONESIA',                       'estado' => 1],
            ['id_pais' =>  81, 'nombre_pais' => 'IRAK',                            'estado' => 1],
            ['id_pais' =>  82, 'nombre_pais' => 'IRÁN',                            'estado' => 1],
            ['id_pais' =>  83, 'nombre_pais' => 'IRLANDA',                         'estado' => 1],
            ['id_pais' =>  84, 'nombre_pais' => 'ISLANDIA',                        'estado' => 1],
            ['id_pais' =>  85, 'nombre_pais' => 'ISLAS MARSHALL',                  'estado' => 1],
            ['id_pais' =>  86, 'nombre_pais' => 'ISLAS SALOMÓN',                   'estado' => 1],
            ['id_pais' =>  87, 'nombre_pais' => 'EL SALVADOR',                     'estado' => 1],
            ['id_pais' =>  88, 'nombre_pais' => 'ISRAEL',                          'estado' => 1],
            ['id_pais' =>  89, 'nombre_pais' => 'ITALIA',                          'estado' => 1],
            ['id_pais' =>  90, 'nombre_pais' => 'JAMAICA',                         'estado' => 1],
            ['id_pais' =>  91, 'nombre_pais' => 'JAPÓN',                           'estado' => 1],
            ['id_pais' =>  92, 'nombre_pais' => 'JORDANIA',                        'estado' => 1],
            ['id_pais' =>  93, 'nombre_pais' => 'KAZAJISTÁN',                      'estado' => 1],
            ['id_pais' =>  94, 'nombre_pais' => 'KENIA',                           'estado' => 1],
            ['id_pais' =>  95, 'nombre_pais' => 'KIRGUISTÁN',                      'estado' => 1],
            ['id_pais' =>  96, 'nombre_pais' => 'KIRIBATI',                        'estado' => 1],
            ['id_pais' =>  97, 'nombre_pais' => 'KUWAIT',                          'estado' => 1],
            ['id_pais' =>  98, 'nombre_pais' => 'LAOS',                            'estado' => 1],
            ['id_pais' =>  99, 'nombre_pais' => 'LESOTO',                          'estado' => 1],
            ['id_pais' => 100, 'nombre_pais' => 'LETONIA',                         'estado' => 1],
            ['id_pais' => 101, 'nombre_pais' => 'LÍBANO',                          'estado' => 1],
            ['id_pais' => 102, 'nombre_pais' => 'LIBERIA',                         'estado' => 1],
            ['id_pais' => 103, 'nombre_pais' => 'LIBIA',                           'estado' => 1],
            ['id_pais' => 104, 'nombre_pais' => 'LIECHTENSTEIN',                   'estado' => 1],
            ['id_pais' => 105, 'nombre_pais' => 'LITUANIA',                        'estado' => 1],
            ['id_pais' => 106, 'nombre_pais' => 'LUXEMBURGO',                      'estado' => 1],
            ['id_pais' => 107, 'nombre_pais' => 'MADAGASCAR',                      'estado' => 1],
            ['id_pais' => 108, 'nombre_pais' => 'MALASIA',                         'estado' => 1],
            ['id_pais' => 109, 'nombre_pais' => 'MALAUI',                          'estado' => 1],
            ['id_pais' => 110, 'nombre_pais' => 'MALDIVAS',                        'estado' => 1],
            ['id_pais' => 111, 'nombre_pais' => 'MALÍ',                            'estado' => 1],
            ['id_pais' => 112, 'nombre_pais' => 'MALTA',                           'estado' => 1],
            ['id_pais' => 113, 'nombre_pais' => 'MARRUECOS',                       'estado' => 1],
            ['id_pais' => 114, 'nombre_pais' => 'MAURICIO',                        'estado' => 1],
            ['id_pais' => 115, 'nombre_pais' => 'MAURITANIA',                      'estado' => 1],
            ['id_pais' => 116, 'nombre_pais' => 'MÉXICO',                          'estado' => 1],
            ['id_pais' => 117, 'nombre_pais' => 'MICRONESIA',                      'estado' => 1],
            ['id_pais' => 118, 'nombre_pais' => 'MOLDAVIA',                        'estado' => 1],
            ['id_pais' => 119, 'nombre_pais' => 'MÓNACO',                          'estado' => 1],
            ['id_pais' => 120, 'nombre_pais' => 'MONGOLIA',                        'estado' => 1],
            ['id_pais' => 121, 'nombre_pais' => 'MONTENEGRO',                      'estado' => 1],
            ['id_pais' => 122, 'nombre_pais' => 'MOZAMBIQUE',                      'estado' => 1],
            ['id_pais' => 123, 'nombre_pais' => 'MYANMAR (BIRMANIA)',               'estado' => 1],
            ['id_pais' => 124, 'nombre_pais' => 'NAMIBIA',                         'estado' => 1],
            ['id_pais' => 125, 'nombre_pais' => 'NAURU',                           'estado' => 1],
            ['id_pais' => 126, 'nombre_pais' => 'NEPAL',                           'estado' => 1],
            ['id_pais' => 127, 'nombre_pais' => 'NICARAGUA',                       'estado' => 1],
            ['id_pais' => 128, 'nombre_pais' => 'NÍGER',                           'estado' => 1],
            ['id_pais' => 129, 'nombre_pais' => 'NIGERIA',                         'estado' => 1],
            ['id_pais' => 130, 'nombre_pais' => 'NORUEGA',                         'estado' => 1],
            ['id_pais' => 131, 'nombre_pais' => 'NUEVA ZELANDA',                   'estado' => 1],
            ['id_pais' => 132, 'nombre_pais' => 'OMÁN',                            'estado' => 1],
            ['id_pais' => 133, 'nombre_pais' => 'PAÍSES BAJOS',                    'estado' => 1],
            ['id_pais' => 134, 'nombre_pais' => 'PAKISTÁN',                        'estado' => 1],
            ['id_pais' => 135, 'nombre_pais' => 'PALAOS',                          'estado' => 1],
            ['id_pais' => 136, 'nombre_pais' => 'PANAMÁ',                          'estado' => 1],
            ['id_pais' => 137, 'nombre_pais' => 'PAPÚA NUEVA GUINEA',              'estado' => 1],
            ['id_pais' => 138, 'nombre_pais' => 'PARAGUAY',                        'estado' => 1],
            ['id_pais' => 139, 'nombre_pais' => 'PERÚ',                            'estado' => 1],
            ['id_pais' => 140, 'nombre_pais' => 'POLONIA',                         'estado' => 1],
            ['id_pais' => 141, 'nombre_pais' => 'PORTUGAL',                        'estado' => 1],
            ['id_pais' => 142, 'nombre_pais' => 'REINO UNIDO',                     'estado' => 1],
            ['id_pais' => 143, 'nombre_pais' => 'REPÚBLICA CENTROAFRICANA',        'estado' => 1],
            ['id_pais' => 144, 'nombre_pais' => 'REPÚBLICA CHECA',                 'estado' => 1],
            ['id_pais' => 145, 'nombre_pais' => 'REPÚBLICA DEMOCRÁTICA DEL CONGO', 'estado' => 1],
            ['id_pais' => 146, 'nombre_pais' => 'REPÚBLICA DOMINICANA',            'estado' => 1],
            ['id_pais' => 147, 'nombre_pais' => 'RUANDA',                          'estado' => 1],
            ['id_pais' => 148, 'nombre_pais' => 'RUMANÍA',                         'estado' => 1],
            ['id_pais' => 149, 'nombre_pais' => 'RUSIA',                           'estado' => 1],
            ['id_pais' => 150, 'nombre_pais' => 'SAMOA',                           'estado' => 1],
            ['id_pais' => 151, 'nombre_pais' => 'SAN CRISTÓBAL Y NIEVES',          'estado' => 1],
            ['id_pais' => 152, 'nombre_pais' => 'SAN MARINO',                      'estado' => 1],
            ['id_pais' => 153, 'nombre_pais' => 'SAN VICENTE Y LAS GRANADINAS',    'estado' => 1],
            ['id_pais' => 154, 'nombre_pais' => 'SANTA LUCÍA',                     'estado' => 1],
            ['id_pais' => 155, 'nombre_pais' => 'SANTO TOMÉ Y PRÍNCIPE',           'estado' => 1],
            ['id_pais' => 156, 'nombre_pais' => 'SENEGAL',                         'estado' => 1],
            ['id_pais' => 157, 'nombre_pais' => 'SERBIA',                          'estado' => 1],
            ['id_pais' => 158, 'nombre_pais' => 'SEYCHELLES',                      'estado' => 1],
            ['id_pais' => 159, 'nombre_pais' => 'SIERRA LEONA',                    'estado' => 1],
            ['id_pais' => 160, 'nombre_pais' => 'SINGAPUR',                        'estado' => 1],
            ['id_pais' => 161, 'nombre_pais' => 'SIRIA',                           'estado' => 1],
            ['id_pais' => 162, 'nombre_pais' => 'SOMALIA',                         'estado' => 1],
            ['id_pais' => 163, 'nombre_pais' => 'SRI LANKA',                       'estado' => 1],
            ['id_pais' => 164, 'nombre_pais' => 'SUAZILANDIA',                     'estado' => 1],
            ['id_pais' => 165, 'nombre_pais' => 'SUDÁFRICA',                       'estado' => 1],
            ['id_pais' => 166, 'nombre_pais' => 'SUDÁN',                           'estado' => 1],
            ['id_pais' => 167, 'nombre_pais' => 'SUDÁN DEL SUR',                   'estado' => 1],
            ['id_pais' => 168, 'nombre_pais' => 'SUECIA',                          'estado' => 1],
            ['id_pais' => 169, 'nombre_pais' => 'SUIZA',                           'estado' => 1],
            ['id_pais' => 170, 'nombre_pais' => 'SURINAM',                         'estado' => 1],
            ['id_pais' => 171, 'nombre_pais' => 'TAILANDIA',                       'estado' => 1],
            ['id_pais' => 172, 'nombre_pais' => 'TANZANIA',                        'estado' => 1],
            ['id_pais' => 173, 'nombre_pais' => 'TAYIKISTÁN',                      'estado' => 1],
            ['id_pais' => 174, 'nombre_pais' => 'TIMOR-LESTE',                     'estado' => 1],
            ['id_pais' => 175, 'nombre_pais' => 'TOGO',                            'estado' => 1],
            ['id_pais' => 176, 'nombre_pais' => 'TONGA',                           'estado' => 1],
            ['id_pais' => 177, 'nombre_pais' => 'TRINIDAD Y TOBAGO',               'estado' => 1],
            ['id_pais' => 178, 'nombre_pais' => 'TÚNEZ',                           'estado' => 1],
            ['id_pais' => 179, 'nombre_pais' => 'TURKMENISTÁN',                    'estado' => 1],
            ['id_pais' => 180, 'nombre_pais' => 'TURQUÍA',                         'estado' => 1],
            ['id_pais' => 181, 'nombre_pais' => 'TUVALU',                          'estado' => 1],
            ['id_pais' => 182, 'nombre_pais' => 'UCRANIA',                         'estado' => 1],
            ['id_pais' => 183, 'nombre_pais' => 'UGANDA',                          'estado' => 1],
            ['id_pais' => 184, 'nombre_pais' => 'URUGUAY',                         'estado' => 1],
            ['id_pais' => 185, 'nombre_pais' => 'UZBEKISTÁN',                      'estado' => 1],
            ['id_pais' => 186, 'nombre_pais' => 'VANUATU',                         'estado' => 1],
            ['id_pais' => 187, 'nombre_pais' => 'VENEZUELA',                       'estado' => 1],
            ['id_pais' => 188, 'nombre_pais' => 'VIETNAM',                         'estado' => 1],
            ['id_pais' => 189, 'nombre_pais' => 'YEMEN',                           'estado' => 1],
            ['id_pais' => 190, 'nombre_pais' => 'YIBUTI',                          'estado' => 1],
            ['id_pais' => 191, 'nombre_pais' => 'ZAMBIA',                          'estado' => 1],
            ['id_pais' => 192, 'nombre_pais' => 'ZIMBABUE',                        'estado' => 1],
            ['id_pais' => 193, 'nombre_pais' => 'TAIWÁN',                          'estado' => 1],
            ['id_pais' => 194, 'nombre_pais' => 'KOSOVO',                          'estado' => 1],
            ['id_pais' => 195, 'nombre_pais' => 'PALESTINA',                       'estado' => 1],
            ['id_pais' => 196, 'nombre_pais' => 'OTRO',                            'estado' => 1],
        ]);
    }
}
